{
 "title": "Smart Home",
 "time": { "from": "2022-01-14T04:21:13.629Z", "to": "2022-01-27T03:52:54.123Z" },
 "panels": [
  {
   "title": "Alarm",
   "type": "stat",
   "description": "Latest alarm status",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  status \nFROM alarm\nORDER BY date_time DESC \nLIMIT 1"
    }
   ]
  },
  {
   "title": "Number of Smoke Detections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select name,count(name) from smoke_sensor where status = 1 group by name;\n"
    }
   ]
  },
  {
   "title": "Number of possible breaches per Motion Sensor",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select ms.name ,count(*)\nfrom alarm a\nleft join motion_sensor ms \non a.date_time = ms.date_time \nwhere a.status  = 1 and ms.status = 1 \nGROUP BY ms.name\n"
    }
   ]
  },
  {
   "title": "Lamps ",
   "type": "stat",
   "description": "The Lamps Panel displays the latest  status of each lamp",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  status as \"Bedroom Lamp -\",\n  description\nFROM lamp\nWHERE\n  name = 'lamp0'\nORDER BY date_time DESC \nLIMIT 1"
    },
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  status as \"Living room Lamp -\",\n  description\nFROM lamp\nWHERE\n  name = 'lamp1'\nORDER BY date_time DESC \nLIMIT 1"
    },
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  status as \"Kitchen Lamp -\",\n  description\nFROM lamp\nWHERE\n  name = 'lamp2'\nORDER BY date_time DESC \nLIMIT 1"
    },
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  status as \"Bathroom Lamp -\",\n  description\nFROM lamp\nWHERE\n  name = 'lamp3'\nORDER BY date_time DESC \nLIMIT 1"
    },
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  status as \"Balcony Lamp -\",\n  description\nFROM lamp\nWHERE\n  name = 'lamp4'\nORDER BY date_time DESC \nLIMIT 1"
    }
   ]
  },
  {
   "title": "Number of possible breaches per Magnet Sensor",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select ms.name ,count(*)\nfrom alarm a\nleft join magnet_sensor ms \non a.date_time = ms.date_time \nwhere a.status  = 1 and ms.status = 1 \nGROUP BY ms.name\n"
    }
   ]
  },
  {
   "title": "Other Devices",
   "type": "stat",
   "description": "Latest devices status",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  status as \"Vacuum -\",\n  description\nFROM vacuum\nORDER BY date_time DESC \nLIMIT 1"
    },
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  status as \"Phone Charger -\",\n  description\nFROM switch\nWHERE name = \"switch0\"\nORDER BY date_time DESC \nLIMIT 1"
    },
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  status as \"Coffee Maker -\",\n  description\nFROM switch\nWHERE name = \"switch1\"\nORDER BY date_time DESC \nLIMIT 1"
    },
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  status as \"Water Heater -\",\n  description\nFROM water_heater\nORDER BY date_time DESC \nLIMIT 1"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "alertlist",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  id\nFROM air_condition\nWHERE\n  $__timeFilter(date_time)\nORDER BY date_time"
    }
   ]
  },
  {
   "title": "Temperature Sensors",
   "type": "gauge",
   "description": "The latest temperatures",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  temp as \"Bedroom Temperature\"\nFROM temp_sensor\nWHERE\n  name = 'sensorTemp0'\nORDER BY date_time DESC \nLIMIT 1"
    },
    {
     "rawSql": "SELECT AVG(temp) as \"Bedroom AVG Temperature\", MAX(date_time) as \"time\" FROM temp_sensor WHERE name = 'sensorTemp0' "
    },
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  temp as \"Living Room Temperature\"\nFROM temp_sensor\nWHERE\n  name = 'sensorTemp1'\nORDER BY date_time DESC \nLIMIT 1"
    },
    {
     "rawSql": "SELECT AVG(temp) as \"Living Room AVG Temperature\", MAX(date_time) as \"time\" FROM temp_sensor WHERE name = 'sensorTemp1' "
    }
   ]
  },
  {
   "title": "Temperature Sensors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  temp AS \"Bedroom\"\nFROM temp_sensor\nWHERE\n  name = 'sensorTemp0'\nORDER BY date_time"
    },
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  temp AS \"Living Room\"\nFROM temp_sensor\nWHERE\n  name = 'sensorTemp1'\nORDER BY date_time"
    }
   ]
  },
  {
   "title": "Light Sensors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "lumens" } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  lm AS \"Bedroom\"\nFROM light_sensor\nWHERE\n  name = 'sensorLight0'\nORDER BY date_time"
    },
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  lm AS \"Living Room\"\nFROM light_sensor\nWHERE\n  name = 'sensorLight1'\nORDER BY date_time"
    },
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  lm AS \"Balcony\"\nFROM light_sensor\nWHERE\n  name = 'sensorLight4'\nORDER BY date_time"
    }
   ]
  },
  {
   "title": "Other Devices",
   "type": "timeseries",
   "description": "TODO",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  status AS \"Water Heater\"\nFROM water_heater\nORDER BY date_time"
    },
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  status AS \"Phone Charger\"\nFROM switch\nwhere name = \"switch0\"\nORDER BY date_time"
    },
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  status AS \"Coffee Maker\"\nFROM switch\nwhere name = \"switch1\"\nORDER BY date_time"
    },
    {
     "rawSql": "SELECT\n  date_time AS \"time\",\n  status AS \"Vacuum Cleaner\"\nFROM vacuum\nORDER BY date_time"
    }
   ]
  }
 ]
}